name: push-image
on:  
  push:
    branches:
      - multi-platform # TODO: move to release workflow
jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/findy-agent-vault:0.1.22 # TODO: set version and latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/findy-agent-vault:0.1.22 # TODO: latest
          cache-to: type=inline

