name: release
on:
  push:
    tags:
      - "*"
jobs:

  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: run test
        run: echo "TODO"

  push-image:
    needs: e2e
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "version=$(cat ./VERSION)" >> $GITHUB_ENV

      - uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/findy-agent-vault:${{ env.version }}
            ghcr.io/${{ github.repository_owner }}/findy-agent-vault:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/findy-agent-vault:latest
          cache-to: type=inline

  merge:
    needs: push-image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: master
      - run: |
          git config --global user.name "findy-agent-vault"
          git config --global user.email "findy-agent-vault"
      - name: merge
        run: |
          git fetch --tags origin
          git merge $GITHUB_REF
          git push origin master
