name: test
on: push
env:
  FAV_DB_PASSWORD: password
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup go
        uses: findy-network/setup-go-action@master
        with:
          linter-config-path: .golangci.yml
      - name: test and measure coverage
        run: make test_cov_out
      - name: upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.txt
          fail_ci_if_error: true
    services:
      postgres:
        image: postgres:13.8-alpine
        ports:
          - 5433:5432
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: vault
  e2e-new:
    runs-on: ubuntu-latest
    steps:
      - name: test e2e flow
        uses: findy-network/e2e-test-action@master
        with:
          service: "vault"
          service-image-path: ./
      - uses: actions/setup-go@v3
        with:
          go-version-file: './go.mod'
      - name: print coverage
        run: go tool covdata percent -i=coverage
        # TODO: print out txt-file
        # add new job to send both txt-files to codecov
      - name: archive logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: coverage files
          path: ./coverage
