name: test
on: push
env:
  FAV_DB_PASSWORD: password
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42
          args: --timeout=5m
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: checkout
        uses: actions/checkout@v2
      - name: test and measure coverage
        run: make test_cov_out
      - name: upload coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.txt
      - name: scan
        run: make scan
    services:
      postgres:
        image: postgres:13.1-alpine
        ports:
          - 5433:5432
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: vault
